### ISSUE TITLE
The special effect of closing the window is weird

### ISSUE THREAD

**Issue by louies0623** [helloSystem/KWin#12] opened 2023-09-03 16:05 UTC
https://github.com/helloSystem/ISO/assets/44593430/5a6e4157-96cf-4d2d-9090-138756b07ddc

CX62
0I38 Live

**Comment by probonopd** [comment] 2023-09-03 19:39
Duplicate of https://github.com/helloSystem/KWin/issues/14

**Closed as completed by probonopd** 2023-09-03 19:39 UTC
Labels: bug

**Comment by probonopd** [comment] 2023-09-03 19:41
Intel GPU, correct?

**Comment by louies0623** [comment] 2023-09-26 04:37
yes

**Comment by probonopd** [comment] 2023-09-26 07:00
Should be fixed now, can you confirm?

**Comment by louies0623** [comment] 2023-09-29 07:55
is fix
